library(tidyverse)
data <- read_csv("diabetic_data_initial.csv")
discharge_ids <- read_csv("discharge.csv")
admission_type_ids <- read_csv("admission_type.csv")
admission_source_ids <- read_csv("admission_type.csv")
